markdown: rdiscount
permalink: /:year/:month/:day/:title/
url: http://nightks.github.io/
highlighter: pygments
author: 猫头鹰患者
exclude: ["Rakefile", "CNAME", "README.md"]
safe: true
paginate: 16 
gems: [jekyll-paginate]
